name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2  # Set your desired Ruby version here

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
    - name: Set up credentials
      run: cp config/master.key config/credentials.yml.enc        
    - name: Run tests
      run: bundle exec rails rswag:specs:swaggerize  # Replace with your test command
