name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      SECRET_KEY_BASE: ${{ secrets.SECRET_KEY_BASE }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2  # Set your desired Ruby version here

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install
        yarn install --check-files
    - name: Print Gem Versions
      run: bundle exec gem list
    - name: Create creds and  master.key
      run: |
        echo "$RAILS_MASTER_KEY" > config/master.key
        chmod 600 config/master.key
    - name: Run tests
      run: |
        bundle exec rails rswag:specs:swaggerize
